- name: install prometheus in Ubuntu
  apt:
    name:
      - prometheus
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install unzip
  package:
    name: unzip

- name: install prometheus in CentOS
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.8.1/prometheus-2.8.1.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution == "CentOS"
